### ISSUE TITLE
安装完成后，上传的图片显示

### ISSUE THREAD

**Issue by Leonhzz** [MliKiowa/GithubStatic#1]
![image](https://user-images.githubusercontent.com/53173411/82541905-b94be000-9b83-11ea-9f2f-80ce17b52aab.png)
只有少数几个图片出现这种问题。
原因不明

**Comment by YueZhiNai** [comment]
可能触发频率限制也可能由于插件问题卡掉了

**Comment by MliKiowa** [comment]
此问题以在处理
