### ISSUE TITLE
无法填入仓库名，如图示。

### ISSUE THREAD

**Issue by CyberpunkZaYu** [MliKiowa/GithubStatic#3]
![屏幕截图 2021-02-22 231636](https://user-images.githubusercontent.com/68150524/108727963-0e2de400-7564-11eb-8b4c-2ff6a87ffd76.png)

**Comment by MliKiowa** [comment]
不用填入仓库名 通过token获取即可得到仓库名 如果token已获取且配置完成 请刷新缓存
